name: Corretor da lista de exercícios da Python Brasil

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuração de Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Correção do Exercício 01 da sessão de Estrutura Sequencial
      run: |
        python -m doctest -f estrutura_sequencial/alo_mundo_01.py
    - name: Correção do Exercício 02 da sessão de Estrutura Sequencial
      run: |
        python -m doctest -f estrutura_sequencial/escreva_um_numero_02.py
